---

  - name: Ensure the Mono GPG key has been imported
    apt_key:
      state: present
      url: "{{ sonarr_mono_gpg_key }}"

  - name: Ensure the Mono APT repository is present
    apt_repository:
      repo: 'deb http://download.mono-project.com/repo/debian wheezy main'
      state: present

  - name: Ensure the Mono Xamarin APT repository is present [Ubuntu]
    apt_repository:
      repo: 'deb http://download.mono-project.com/repo/debian wheezy-apache24-compat main'
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Ensure the Mono Xamarin APT repository is present [Debian]
    apt_repository:
      repo: 'deb http://download.mono-project.com/repo/debian wheezy-libjpeg62-compat main'
      state: present
    when: ansible_distribution == "Debian"

  - name: Ensure libmediainfo0 is installed
    package: name=libmediainfo0 state=present
