Vagrant.configure(2) do | config |
  config.ssh.insert_key = false
  config.ssh.username = 'vagrant'
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  # Debian 8
  config.vm.define "debian8" do |sonarr|
    sonarr.vm.hostname = "debian8.dev"
    sonarr.vm.box = "debian/jessie64"
    sonarr.vm.network :private_network, ip: "192.168.54.2"
    sonarr.vm.network "forwarded_port", guest: 8989, host: 5959
  end

  # Ubuntu 15.04
  config.vm.define "ubuntu15" do |sonarr|
    sonarr.vm.hostname = "ubuntu15.dev"
    sonarr.vm.box = "ubuntu/vivid64"
    sonarr.vm.network :private_network, ip: "192.168.54.3"
    sonarr.vm.network "forwarded_port", guest: 8989, host: 6969
  end

  # CentOS 7
  config.vm.define "centos7" do |sonarr|
    sonarr.vm.hostname = "centos7.dev"
    sonarr.vm.box = "geerlingguy/centos7"
    sonarr.vm.network :private_network, ip: "192.168.54.4"
    sonarr.vm.network "forwarded_port", guest: 8989, host: 7979
  end

  # Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.groups = {
      "sonarr_servers" => ["debian8", "ubuntu15", "centos7"],
      "all_groups:children" => ["sonarr_servers"]
    }

    ansible.sudo = true
    ansible.playbook = "provision.yml"
  end
end
